language: node_js
node_js:
  - 13

services:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

# Scripts to be run such as tests
before_script:
  - echo "no tests"

script:
  - docker --version # print the version for logging
  - docker build -t udagram-api-feed-two ./udagram-api-feed
  - docker tag udagram-api-feed ezraone/udagram-api-feed:v12
  
  - docker build -t udagram-api-user-two ./udagram-api-user
  - docker tag udagram-api-user ezraone/udagram-api-user:v12

  - docker build -t udagram-frontend-two ./udagram-frontend
  - docker tag udagram-frontend ezraone/udagram-frontend:local

  - docker build -t reverseproxy-two ./udagram-reverseproxy
  - docker tag udagram-api-feed ezraone/reverseproxy:v10

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push ezraone/udagram-api-feed-two:v12
  - docker push ezraone/udagram-api-user-two:v12
  - docker push ezraone/udagram-frontend-two:local
  - docker push ezraone/reverseproxy-two:v10